##################################################################################
# Cloudify vSphere built in types and plugins definitions.
##################################################################################

imports:
    - http://www.getcloudify.org/spec/cloudify/3.1rc1/types.yaml

plugins:
    vsphere:
        executor: central_deployment_agent
        source: /home/cloudify-vsphere-plugin-3.1-port.zip

node_types:
    cloudify.vsphere.server:
        derived_from: cloudify.types.host
        properties:
            server: {}
            networking: {}
            connection_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: vsphere.server_plugin.server.start
                    inputs: {}
                stop:
                    implementation: vsphere.server_plugin.server.stop
                    inputs: {}
                shutdown_guest:
                    implementation: vsphere.server_plugin.server.shutdown_guest
                    inputs: {}
                delete:
                    implementation: vsphere.server_plugin.server.delete
                    inputs: {}
            cloudify.interfaces.host:
                get_state:
                    implementation: vsphere.server_plugin.server.get_state
                    inputs: {}

    cloudify.vsphere.network:
        derived_from: cloudify.types.network
        properties:
            network: {}
            connection_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vsphere.network_plugin.network.create
                    inputs: {}
                delete:
                    implementation: vsphere.network_plugin.network.delete
                    inputs: {}

    cloudify.vsphere.storage:
        derived_from: cloudify.types.volume
        properties:
            storage: {}
            connection_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vsphere.storage_plugin.storage.create
                    inputs: {}
                delete:
                    implementation: vsphere.storage_plugin.storage.delete
                    inputs: {}
