##################################################################################
# Cloudify vSphere built in types and plugins definitions.
##################################################################################

imports:
    - "http://www.getcloudify.org/spec/cloudify/3.0/types.yaml"

plugins:
    server_plugin:
        derived_from: cloudify.plugins.manager_plugin
        properties:
            url: http://37.58.121.34:8080/cloudify-vsphere-plugin-1-develop.zip
    network_plugin:
        derived_from: cloudify.plugins.manager_plugin
        properties:
            url: http://37.58.121.34:8080/cloudify-vsphere-plugin-1-develop.zip

types:
    cloudify.vsphere.server:
        derived_from: cloudify.types.host
        properties:
            - server
            - networking
            - connection_config
        interfaces:
            cloudify.interfaces.lifecycle:
                - start: server_plugin.server.start
                - stop: server_plugin.server.stop
                - shutdown_guest: server_plugin.server.shutdown_guest
                - delete: server_plugin.server.delete
            cloudify.interfaces.host:
                - get_state: server_plugin.server.get_state

    cloudify.vsphere.network:
        derived_from: cloudify.types.network
        properties:
            - network
            - connection_config: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: network_plugin.network.create
                - delete: network_plugin.network.delete

    cloudify.vsphere.storage:
        derived_from: cloudify.types.volume
        properties:
            - storage
            - connection_config: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: storage_plugin.storage.create
                - delete: storage_plugin.storage.delete

relationships:
    cloudify.vsphere.server_connected_to_network:
        derived_from: cloudify.relationships.connected_to

    cloudify.vsphere.storage_connected_to_server:
        derived_from: cloudify.relationships.connected_to
