##################################################################################
# Cloudify vSphere built in types and plugins definitions.
##################################################################################

imports:
    - "http://www.getcloudify.org/spec/cloudify/3.1/types.yaml"

plugins:
    vsphere:
        executor: central_deployment_agent
        source: http://127.0.0.1/cloudify-vsphere-plugin/archive/develop.zip

types:
    cloudify.vsphere.server:
        derived_from: cloudify.types.host
        properties:
            - server
            - networking
            - connection_config
        interfaces:
            cloudify.interfaces.lifecycle:
                - start: vsphere.server_plugin.server.start
                - stop: vsphere.server_plugin.server.stop
                - shutdown_guest: vsphere.server_plugin.server.shutdown_guest
                - delete: vsphere.server_plugin.server.delete
            cloudify.interfaces.host:
                - get_state: vsphere.server_plugin.server.get_state

    cloudify.vsphere.network:
        derived_from: cloudify.types.network
        properties:
            - network
            - connection_config: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: vsphere.network_plugin.network.create
                - delete: vsphere.network_plugin.network.delete

    cloudify.vsphere.storage:
        derived_from: cloudify.types.volume
        properties:
            - storage
            - connection_config: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: vsphere.storage_plugin.storage.create
                - delete: vsphere.storage_plugin.storage.delete

relationships:
    cloudify.vsphere.server_connected_to_network:
        derived_from: cloudify.relationships.connected_to

    cloudify.vsphere.storage_connected_to_server:
        derived_from: cloudify.relationships.connected_to
